version: 0.2

phases:
  install:
    runtime-versions:
        dotnet: latest
  build:
    commands:
      - dotnet restore
      - dotnet publish -o ./build-output
artifacts:
  files:
    - ./build-output/**/*